security:

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
  providers:
    in_memory:
      memory:
        users:
          demo:
            password: demo
            roles: ROLE_ADMIN
#  encoders:
#    App\Entity\Admin:
#      algorithm: bcrypt
#      cost: 12
#  providers:
#      from_database:
#        entity:
#          class: App\Entity\Admin
#          property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      logout:
        path: /logout
        target: /login

      http_basic: true
      form_login:
        check_path: /login


  access_control:
    - {path: ^/home , roles: ROLE_ADMIN}
