security:

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  providers:
    in_memory:
      memory:
        users:
          demo:
            password: demo
            roles: ROLE_ADMIN
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      logout:
        path: /logout
        target: /

      #http_basic: true
      form_login:
        check_path: login


  access_control:
    - {path: ^/admin, roles: ROLE_ADMIN}
